### ISSUE TITLE
Performance and Scalability

### ISSUE THREAD

**Issue by BobcatProgrammer** [BorisWilhelms/serverlesswebapi#1]
Hi @BorisWilhelms,

have you done any performance tests with this and how well it scales? Do the calls to the TestServer count towards the HTTP Limit of a function app?

I really like your idea of getting the full ASP.NET experience without the hassle of thinking about scaling.

Thanks,
Simon

**Comment by ghstahl** [comment]
At the heart of it, you are simply calling a personal library called TestServer via a specialized HttpClient that is basically used to proxy to that personal library.  The only thing that Azure knows is that an HTTP trigger hit that main entry point.  What you do after that is your business.  

I have yet to run load tests on this, but I would hope it is similar to "dotnet run myapp.dll"

I have taken this one step further by introducing the ability to run multiple apps in a single function, etc.
[Asp.Net-Core-2.1-app-as-a-tenant](https://github.com/ghstahl/Asp.Net-Core-2.1-app-as-a-tenant)

It is just a router calling another router and so on.  

My hope is that Azure may have inadvertently created the one and only way to deploy an asp.net core app.  i.e. why use PaaS or IIS or VMs when Functions rock.  

Perhaps, in the end, everything will be nothing more than Azure Functions.  BTW: The AWS have the same thing going on with Lambas.  You can deploy your app in lambda as well.
